// <auto-generated />
using MP_EF_HeberAndrade;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MP_EF_HeberAndrade.Migrations
{
    [DbContext(typeof(CustomTreatmentContext))]
    partial class CustomTreatmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MP_EF_HeberAndrade.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DietDaysProgram")
                        .HasColumnType("int");

                    b.Property<string>("DietName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DietSelect")
                        .HasColumnType("int");

                    b.Property<string>("DietType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("MP_EF_HeberAndrade.Diet1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DietDaysProgram")
                        .HasColumnType("int");

                    b.Property<string>("DietName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DietSelect")
                        .HasColumnType("int");

                    b.Property<string>("DietType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets1");
                });
#pragma warning restore 612, 618
        }
    }
}
